In [2]:
from facenet_pytorch import MTCNN, InceptionResnetV1, fixed_image_standardization, training
import torch
from torchvision import datasets, transforms
import cv2
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity as ssim
import time
import os

/home/pj00/anaconda3/envs/CVenv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Load model and tracker

In [3]:
# set device
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print('Current device: {}'.format(device))

Current device: cuda:0


In [4]:
mtcnn = MTCNN(
    image_size=160,
    margin=0,
    min_face_size=20,
    thresholds=[0.6, 0.7, 0.7],
    factor=0.709,
    post_process=False,
    device=device
)

resnet = InceptionResnetV1(classify=True, pretrained='vggface2', num_classes=2).to(device)
weight_path = '/home/pj00/projects/Github/online_face_recognition_and_detection/model_weights'
current_versions = os.listdir(weight_path)
current_max = max(current_versions, key = lambda x: int(x.split('.')[0]))
resnet.load_state_dict(torch.load(os.path.join(weight_path, current_max)))
resnet.to(device)
resnet.eval()
print(current_max)

9.pt


## Functions

In [14]:
def frame_norm(frame_bgr):
    temp_frame = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2GRAY)
    temp_frame = cv2.normalize(temp_frame, None, 0, 1.0, cv2.NORM_MINMAX, dtype=cv2.CV_32F)
    return temp_frame

def generate_bboxes(probs, threshold, faces):
    thres_probs = np.where(probs>threshold)
    bboxes = []
    for idx in thres_probs[0]:
        x0, y0, x1, y1 = faces[idx].astype(int)
        w = x1 - x0
        h = y1 - y0

        bbox = (x0, y0, w, h)
        bboxes.append(bbox)
    return bboxes

def createTracker(bboxes):
    multiTracker = cv2.legacy.MultiTracker_create()
    for bbox in bboxes:
        multiTracker.add(cv2.legacy.TrackerKCF_create(), frame, bbox)
    success = True
    
    return multiTracker, success

def frame_rectangles(frame, bboxes, color_ids):
    for bbox, color in zip(bboxes, color_ids):
        p1 = (int(bbox[0]), int(bbox[1]))
        p2 = (int(bbox[0] + bbox[2]), int(bbox[1] + bbox[3]))
        cv2.rectangle(frame, p1, p2, color, 2, 1)
    return frame

def confirm_id(frame, bboxes, id_thresh=0.8):
    trans = transforms.Compose([
                        np.float32,
                        transforms.ToTensor()])
    colors = []
    for bbox in bboxes:
        x, y, w, h = bbox
#         face = torch.Tensor(frame[y:y+160, x:x+160, ::-1].copy()).permute(2, 0, 1).to(device)
        face = trans(frame[y:y+160, x:x+160, ::-1].copy()).to(device)

        embeddings = resnet(torch.unsqueeze(face, 0).to(device)).detach().cpu()
        print(softmax(embeddings))
        if torch.argmax(softmax(embeddings)):
            if torch.max(softmax(embeddings)) > id_thresh:
                colors.append((0, 255, 0))
            else:
                colors.append((0, 0, 255))
        else:
            colors.append((0, 0, 255))
    return colors

## Start recording

In [6]:
cap = cv2.VideoCapture(0)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

print(width, height)

640 480


[ WARN:0@1.142] global /croot/opencv-suite_1691620365762/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created


In [9]:
multiTracker = cv2.legacy.MultiTracker_create()

In [15]:
threshold = 0.8
ssim_thresh = 0.80
sampling_frames = 30
softmax = torch.nn.Softmax()

In [18]:
prev = np.zeros([height, width]).astype('uint8')
prev = cv2.normalize(prev, None, 0, 1.0, cv2.NORM_MINMAX, dtype=cv2.CV_32F)

ssims = []
frame_counter = 0
resnet.eval()

start = time.time()
while True:
    ret, frame = cap.read()
    
    # Update tracker
    success, bboxes = multiTracker.update(frame)
    
    current = frame.copy()
    current = frame_norm(current)
    
    if not frame_counter%sampling_frames:
        ssims.append(ssim(current, prev, data_range=2))
        prev = current.copy()
    
        # major changes in image
        if ssims[-1] < ssim_thresh:
            # detect faces within the frame
            faces, probs = mtcnn.detect(frame[:,:,::-1])

            # run only if faces are detected
            if probs.any():
                bboxes = generate_bboxes(probs, threshold, faces)
                color_ids = confirm_id(frame, bboxes)
                #initiate tracker
                if len(bboxes):
                    multiTracker, success = createTracker(bboxes)
    
    if success:
        frame = frame_rectangles(frame, bboxes, color_ids)
            
    cv2.imshow('Tracked person', frame)
    
    # Exit if ESC pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    frame_counter += 1
    
    
    
end = time.time()
cv2.waitKey(0)
cv2.destroyAllWindows()

tensor([[0.1569, 0.8431]])
tensor([[0.0926, 0.9074]])
tensor([[0.9445, 0.0555]])
tensor([[0.2266, 0.7734]])
tensor([[0.3826, 0.6174]])
tensor([[9.9922e-01, 7.7566e-04]])
tensor([[0.2326, 0.7674]])
tensor([[0.5423, 0.4577]])
tensor([[0.1330, 0.8670]])
tensor([[0.2283, 0.7717]])
tensor([[0.1636, 0.8364]])
tensor([[0.1948, 0.8052]])
tensor([[0.1840, 0.8160]])
tensor([[0.1626, 0.8374]])
tensor([[0.1657, 0.8343]])
tensor([[0.1626, 0.8374]])
tensor([[0.2167, 0.7833]])
tensor([[0.2014, 0.7986]])
tensor([[0.2558, 0.7442]])
tensor([[0.2304, 0.7696]])
tensor([[0.1640, 0.8360]])
tensor([[0.1736, 0.8264]])
tensor([[0.1818, 0.8182]])
tensor([[0.2968, 0.7032]])
tensor([[0.1703, 0.8297]])
tensor([[0.1787, 0.8213]])
tensor([[0.1245, 0.8755]])
tensor([[0.8475, 0.1525]])
tensor([[0.1130, 0.8870]])
tensor([[0.1681, 0.8319]])
tensor([[0.4144, 0.5856]])
tensor([[0.9981, 0.0019]])
tensor([[0.1455, 0.8545]])
tensor([[0.1753, 0.8247]])
tensor([[0.6919, 0.3081]])
tensor([[0.1441, 0.8559]])
tensor([[0.2819, 0.7

In [ ]:
plt.plot(ssims)

In [ ]:
print(frame_counter/(end-start))

In [ ]:
_, frame = cap.read()

In [ ]:
plt.imshow(frame[:, :, ::-1])

In [ ]:
faces, probs = mtcnn.detect(frame[:,:,::-1])
bboxes = generate_bboxes(probs, threshold, faces)
color_ids = confirm_id(frame, bboxes)